### ISSUE TITLE
Drop Support for Python 3.6

### ISSUE THREAD

**Issue by Samylov-Mikhail** [django-ftl/fluent-compiler#22]
# Reasons

1. `django-ftl` doesn't support Python 3.6.
2. Since 2021-12-23 Python 3.6 is EOL (see [PEP 494](https://peps.python.org/pep-0494/)).
3. Type annotation improvements in Python 3.7 (see [PEP 563](https://peps.python.org/pep-0563/)).

# Possibly changes

* Use `dataclasses` instead of `attrs`.
* Use builtin `dict` instead of `collections.OrderedDict`.

See also [What’s New In Python 3.7](https://docs.python.org/3/whatsnew/3.7.html).

**Comment by spookylukey** [comment]
If possible, I'd rather not drop Python 3.6 yet - for one thing, because fluent.runtime still supports it, and I'd like fluent-compiler to be a drop in replacement. For the level of type annotations required for #14 (i.e. user facing type annotations, rather than internals), I don't think we'll need much that is only available in Python 3.7. Is there something that can't be typed easily in Python 3.6 that we need, and is available in 3.7?

**Comment by Samylov-Mikhail** [comment]
> Is there something that can't be typed easily in Python 3.6 that we need, and is available in 3.7?

No, there's nothing. In Python 3.7 added the optional feature that type annotations are not executed at runtime, which improves performance.

I agree with you! So I've closed this issue.
